"use strict";(()=>{var e={};e.id=3703,e.ids=[3703],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},23869:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>m,patchFetch:()=>g,requestAsyncStorage:()=>f,routeModule:()=>p,serverHooks:()=>d,staticGenerationAsyncStorage:()=>c});var o={};r.r(o),r.d(o,{GET:()=>u});var a=r(49303),n=r(88716),i=r(60670),l=r(55661),s=r(60707);async function u(){let e=await {rules:[{userAgent:"*",allow:"/",disallow:["/api/","/admin/","/prisijungti","/forumas/naujas"]},{userAgent:["GPTBot","ChatGPT-User","Google-Extended","Bingbot","Applebot-Extended"],allow:["/","/api/search/","/api/kindergartens","/api/aukles","/api/bureliai","/api/specialists","/api/cities","/llms.txt","/llms-full.txt","/.well-known/ai-plugin.json","/api/openapi.json"],disallow:["/admin/","/api/admin/","/api/auth/","/api/favorites","/api/metrics"]}],sitemap:"https://manovaikai.lt/sitemap.xml"},t=(0,s.resolveRouteData)(e,"robots");return new l.NextResponse(t,{headers:{"Content-Type":"text/plain","Cache-Control":"public, max-age=0, must-revalidate"}})}let p=new a.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/robots.txt/route",pathname:"/robots.txt",filename:"robots",bundlePath:"app/robots.txt/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Frobots.txt%2Froute&filePath=%2Fhome%2Fopenclaw%2FProjects%2Fvaikai-lt%2Fsrc%2Fapp%2Frobots.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:o}),{requestAsyncStorage:f,staticGenerationAsyncStorage:c,serverHooks:d}=p,m="/robots.txt/route";function g(){return(0,i.patchFetch)({serverHooks:d,staticGenerationAsyncStorage:c})}},60707:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveManifest:function(){return i},resolveRobots:function(){return a},resolveRouteData:function(){return l},resolveSitemap:function(){return n}});let o=r(91389);function a(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,o.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,o.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,o.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,o.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function n(e){let t=e.some(e=>Object.keys(e.alternates??{}).length>0),r="";for(let a of(r+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var o;r+=`<url>
<loc>${a.url}</loc>
`;let e=null==(o=a.alternates)?void 0:o.languages;if(e&&Object.keys(e).length)for(let t in e)r+=`<xhtml:link rel="alternate" hreflang="${t}" href="${e[t]}" />
`;if(a.lastModified){let e=a.lastModified instanceof Date?a.lastModified.toISOString():a.lastModified;r+=`<lastmod>${e}</lastmod>
`}a.changeFrequency&&(r+=`<changefreq>${a.changeFrequency}</changefreq>
`),"number"==typeof a.priority&&(r+=`<priority>${a.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function i(e){return JSON.stringify(e)}function l(e,t){return"robots"===t?a(e):"sitemap"===t?n(e):"manifest"===t?i(e):""}},91389:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function o(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveArray:function(){return r},resolveAsArrayOrUndefined:function(){return o}})}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[8948,2518],()=>r(23869));module.exports=o})();